services:
  - type: web
    name: portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node node_modules/.bin/next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.20.0
      - key: NODE_ENV
        value: production
